### ISSUE TITLE
Research available components for graph display in angular2

### ISSUE THREAD

**Issue by andrewbroekman** [CodingInfinity/Benchmark-Web-Interface#35]

**Comment by BrentonWatt** [comment]
https://www.sitepoint.com/chart-component-angular2-fusioncharts/

**Comment by BrentonWatt** [comment]
https://blog.zingchart.com/2016/03/16/angular-2-example-zingchart/

**Comment by BrentonWatt** [comment]
From the research I've done, although I stand to correction, we will need to use an external library such as the two mentioned above in order to implement a graph/chart component in angular2

**Comment by BrentonWatt** [comment]
https://vaadin.com/charts

In order to implement a chart in vaadin, needs to be implemented as a component and the data series can be pulled from an array, we can save the data from the benchmarks in an array to pipe them directly into the component. Just a suggestion.
